// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:b46294e5-4e2c-4f8d-b2eb-a6162266b337",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_5kjBKgo2k",
    "aws_user_pools_web_client_id": "2m0f2gubgup663gttdm1q16qne",
    "oauth": {},
    "aws_mobile_analytics_app_id": "f49f5d11a8634f39aba838a29342f969",
    "aws_mobile_analytics_app_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://xvd73rro2rcfvf75gua2b6fuqi.appsync-api.eu-west-2.amazonaws.com/graphql",
    "graphql_endpoint": 'https://xvd73rro2rcfvf75gua2b6fuqi.appsync-api.eu-west-2.amazonaws.com/graphql',
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
